<template>
  <article
    ref="rootRef"
    @dragend="onDragEnd"
    @dragover="onDragOver"
    @dragstart="onDragStart"
    :draggable="draggable">
    <slot></slot>
  </article>
</template>

<script>

import { dnd } from './useDnD'
import { ref, inject } from 'vue'

/// Custom drag and drop related events generated by a list item
const useDnDItemEvents = function(props, emit, rootRef, copy, list) {

  // Item started being dragged
  function onDragStart(evt) {
    // Set effect
    const effect = copy ? 'copy' : 'move'
    evt.dataTransfer.dropEffect = effect
    evt.dataTransfer.effectAllowed = effect

    // Set drag image
    const rect = rootRef.value.getBoundingClientRect()
    const coords = {
      x: evt.clientX - rect.left,
      y: evt.clientY - rect.top
    }
    evt.dataTransfer.setDragImage(rootRef.value, coords.x, coords.y)

    // Emit event
    dnd.start(list, copy? JSON.parse(JSON.stringify(props.item)) : props.item)
  }

  // Something's being dragged over this list item
  function onDragOver(evt) {
    evt.preventDefault()
    emit('dnd:drag-over', {index: props.index})
  }

  // Item stopped being dragged
  function onDragEnd(evt) {
    evt.preventDefault()
    dnd.end()
    if(evt.dataTransfer.dropEffect == 'none') {
      // dnd canceled
      // ATMW raising events doesn't work from this
      // handler; get back to this when figuring it out
      // and raise a `dnd:cancel` event in order to give
      // consumers a chance to rollback state changes
    }
  }

  return {
    onDragStart,
    onDragEnd,
    onDragOver
  }
}

export default {
  name: 'DnDListItem',
  props: {
    item: {
      required: true
    },
    index: {
      required: true
    }
  },
  emits: ['dnd:drag-over'],
  setup(props, { emit }) {
    const rootRef = ref(null)

    // Get injected props
    const list = inject('dnd-list', null)
    const draggable = inject('dnd-draggable', true)
    const copy = inject('dnd-copy', false)

    return {
      rootRef,
      draggable,
      ...useDnDItemEvents(props, emit, rootRef, copy, list),
    }
  },
}

</script>
