<template>
  <div ref="rootRef" @dragstart="onDragStart" @dragend="onDragEnd" :draggable="draggable">
    <div style="pointer-events: none;"><slot></slot></div>
  </div>
</template>

<script>

import { ref, inject, onBeforeMount, onBeforeUnmount } from 'vue'

/// Custom drag and drop related events generated by a list item
const useDnDItemEvents = function(props, emit, rootRef, copy, horizontal) {

  // Item started being dragged
  const onDragStart = (evt) => {

    // Set effect
    const effect = copy ? 'copy' : 'move'
    evt.dataTransfer.dropEffect = effect
    evt.dataTransfer.effectAllowed = effect

    // Set drag image
    const rect = rootRef.value.getBoundingClientRect()
    const coords = {
      x: evt.clientX - rect.left,
      y: evt.clientY - rect.top
    }
    evt.dataTransfer.setDragImage(rootRef.value, coords.x, coords.y)

    // Emit event
    emit('dnd:drag-started', {index: props.index})
  }

  // Item stopped being dragged
  const onDragEnd = () => {
    emit('dnd:drag-ended', {index: props.index})
  }

  // Check if something is being dragged over this item.
  // Working with window events because they are more reliable, not
  // being affected by the item's children generating DnD events.
  function dragOverWindow(evt) {
    evt.preventDefault()    
    const rect = rootRef.value.getBoundingClientRect()
    const draggingOver =
      evt.clientY >= rect.top &&
      evt.clientY <= rect.bottom &&
      evt.clientX >= rect.left &&
      evt.clientX <= rect.right
    if (draggingOver) {
      emit('dnd:drag-over', {index: props.index})
    }
  }

  // TODO: try to find other solution than wiring tons of handlers, one for each
  // item in the list
  onBeforeMount(() => {
    window.addEventListener("dragover", dragOverWindow)
  })

  onBeforeUnmount(() => {
    window.removeEventListener("dragover", dragOverWindow)
  })

  return {
    onDragStart,
    onDragEnd
  }
}

export default {
  name: "DnDListItem",
  props: {
    item: {
      required: true
    },
    index: {
      required: true
    }
  },
  setup(props, { emit }) {
    const rootRef = ref(null)

    const draggable = inject('dnd-draggable', true)
    const copy = inject('dnd-copy', false)
    const horizontal = inject('dnd-horizontal', false)

    return {
      rootRef,
      draggable,
      ...useDnDItemEvents(props, emit, rootRef, copy, horizontal),
    }
  },
}

</script>
