<template>
  <div ref="rootRef" @dragstart="onDragStart" @dragend="onDragEnd" :draggable="draggable">
    <div style="pointer-events: none;"><slot></slot></div>
  </div>
</template>

<script>

import { ref, onBeforeMount, onBeforeUnmount } from 'vue'

/// Custom drag and drop related events generated by a list item
const useDnDItemEvents = function(props, emit, rootRef) {

  // Item started being dragged
  const onDragStart = (evt) => {
    const effect = props.copy ? 'copy' : 'move'
    evt.dataTransfer.dropEffect = effect
    evt.dataTransfer.effectAllowed = effect
    emit('dnd:drag-started', {index: props.index})
  }

  // Item stopped being dragged
  const onDragEnd = () => {
    emit('dnd:drag-ended', {index: props.index})
  }

  // Check if something is being dragged over this item.
  // Working with window events because they are more reliable, not
  // being affected by the item's children generating DnD events.
  function dragOverWindow(evt) {
    evt.preventDefault()    
    const rect = rootRef.value.getBoundingClientRect()
    const draggingOver =
      evt.clientY >= rect.top &&
      evt.clientY <= rect.bottom &&
      evt.clientX >= rect.left &&
      evt.clientX <= rect.right
    if (draggingOver) {
      const dropZoneHeight = (rect.bottom - rect.top) / 3; // 1/3 of the item height
      // Check if the mouse is in the top or bottom 1/3 of the item
      const draggedOverTopDropZone = (evt.clientY < rect.top + dropZoneHeight)
      const draggedOverBottomDropZone = (evt.clientY > rect.bottom - dropZoneHeight)

      // Emit a custom event with the item's index and the position
      if (draggedOverTopDropZone) {
        emit('dnd:drag-over', {index: props.index, position: 'before'})
      } else if (draggedOverBottomDropZone) {
        emit('dnd:drag-over', {index: props.index, position: 'after'})
      }
    }
  }

  // TODO: try to find other solution than wiring tons of handlers, one for each
  // item in the list
  onBeforeMount(() => {
    window.addEventListener("dragover", dragOverWindow)
  })

  onBeforeUnmount(() => {
    window.removeEventListener("dragover", dragOverWindow)
  })

  return {
    onDragStart,
    onDragEnd
  }
}

export default {
  name: "DnDListItem",
  props: {
    item: {
      required: true
    },
    index: {
      required: true
    },
    draggable: {
      type: Boolean,
      default: false
    },
    copy: {
      type: Boolean,
      default: false
    }
  },
  setup(props, { emit }) {
    const rootRef = ref(null)
    return {
      rootRef,
      ...useDnDItemEvents(props, emit, rootRef),
    }
  },
}

</script>
